import * as THREE from 'three';
import type { TrackState } from '@sim/logistics/TrackState';

const TRACK_Y_OFFSET = 0.12; // slightly above ground to avoid z-fighting
const TEAM_COLORS = [0x4488ff, 0xff4444];
const TRACK_OPACITY = 0.5;

/**
 * Renders track lines on the ground for each team's active train route.
 * Rebuilds geometry each frame from the TrackState active route — cheap with
 * the ~100 waypoints generated by the Catmull-Rom spline.
 */
export class TrackRenderer {
  private scene: THREE.Scene;
  private trackLines = new Map<number, THREE.Line>();
  private materials = new Map<number, THREE.LineBasicMaterial>();
  private playerTeam = 0;

  constructor(scene: THREE.Scene) {
    this.scene = scene;
  }

  setPlayerTeam(team: number): void {
    this.playerTeam = team;
  }

  sync(trackState: TrackState, teamCount: number): void {
    for (let team = 0; team < teamCount; team++) {
      const ts = trackState.get(team);
      const route = ts.activeRoute;

      // Skip rendering enemy tracks in non-spectator mode
      if (this.playerTeam >= 0 && team !== this.playerTeam) {
        this.removeTrack(team);
        continue;
      }

      if (route.length < 2) {
        this.removeTrack(team);
        continue;
      }

      this.rebuildTrack(team, route);
    }
  }

  private rebuildTrack(team: number, route: { x: number; y: number; z: number }[]): void {
    // Reuse existing Line object, just replace its geometry
    let line = this.trackLines.get(team);
    let material = this.materials.get(team);

    if (!material) {
      material = new THREE.LineBasicMaterial({
        color: TEAM_COLORS[team] ?? 0xffffff,
        transparent: true,
        opacity: TRACK_OPACITY,
        depthTest: true,
      });
      this.materials.set(team, material);
    }

    // Build points array
    const positions = new Float32Array(route.length * 3);
    for (let i = 0; i < route.length; i++) {
      positions[i * 3] = route[i].x;
      positions[i * 3 + 1] = route[i].y + TRACK_Y_OFFSET;
      positions[i * 3 + 2] = route[i].z;
    }

    if (line) {
      // Update existing geometry in-place
      const geo = line.geometry;
      geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
      geo.setDrawRange(0, route.length);
      geo.computeBoundingSphere();
    } else {
      const geometry = new THREE.BufferGeometry();
      geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
      line = new THREE.Line(geometry, material);
      line.renderOrder = -1;
      line.frustumCulled = false;
      this.scene.add(line);
      this.trackLines.set(team, line);
    }
  }

  private removeTrack(team: number): void {
    const existing = this.trackLines.get(team);
    if (existing) {
      this.scene.remove(existing);
      existing.geometry.dispose();
      this.trackLines.delete(team);
    }
  }

  dispose(): void {
    for (const [team] of this.trackLines) {
      this.removeTrack(team);
    }
    for (const [, mat] of this.materials) {
      mat.dispose();
    }
    this.materials.clear();
  }
}
