import * as THREE from 'three';
import type { TrackState } from '@sim/logistics/TrackState';
import type { FogOfWarState } from '@sim/fog/FogOfWarState';

const TRACK_Y_OFFSET = 0.12; // slightly above ground to avoid z-fighting
const TEAM_COLORS = [0x4488ff, 0xff4444];
const TRACK_OPACITY = 0.5;
const RAIL_GAUGE = 0.4;           // total distance between rails (wu)
const HALF_GAUGE = RAIL_GAUGE / 2; // offset per side from centerline

interface TrackLinePair {
  left: THREE.Line | THREE.LineSegments;
  right: THREE.Line | THREE.LineSegments;
}

/**
 * Renders dual parallel track lines on the ground for each team's active train route.
 * Rebuilds geometry each frame from the TrackState active route — cheap with
 * the ~100 waypoints generated by the Catmull-Rom spline.
 *
 * Enemy tracks are rendered per-segment with fog-of-war filtering:
 * only segments where at least one endpoint is currently visible are shown.
 */
export class TrackRenderer {
  private scene: THREE.Scene;
  private trackLines = new Map<number, TrackLinePair>();
  private materials = new Map<number, THREE.LineBasicMaterial>();
  private playerTeam = 0;
  private fogState: FogOfWarState | null = null;

  constructor(scene: THREE.Scene) {
    this.scene = scene;
  }

  setPlayerTeam(team: number): void {
    this.playerTeam = team;
  }

  setFogState(fogState: FogOfWarState): void {
    this.fogState = fogState;
  }

  sync(trackState: TrackState, teamCount: number): void {
    for (let team = 0; team < teamCount; team++) {
      const ts = trackState.get(team);
      const route = ts.activeRoute;

      if (route.length < 2) {
        this.removeTrack(team);
        continue;
      }

      // Enemy tracks: fog-filtered per-segment rendering
      if (this.playerTeam >= 0 && team !== this.playerTeam) {
        this.rebuildEnemyTrack(team, route);
        continue;
      }

      this.rebuildTrack(team, route);
    }
  }

  /**
   * Compute left and right rail positions for each waypoint in the route.
   * Uses central-difference tangent estimation for smooth perpendiculars.
   */
  private computeRailOffsets(
    route: { x: number; y: number; z: number }[],
    closedLoop: boolean,
  ): { left: number[]; right: number[] } {
    const len = route.length;
    const left: number[] = [];
    const right: number[] = [];

    for (let i = 0; i < len; i++) {
      // Determine prev and next indices for tangent estimation
      let prevIdx: number;
      let nextIdx: number;
      if (closedLoop) {
        prevIdx = (i - 1 + len) % len;
        nextIdx = (i + 1) % len;
      } else {
        prevIdx = Math.max(0, i - 1);
        nextIdx = Math.min(len - 1, i + 1);
      }

      let dx = route[nextIdx].x - route[prevIdx].x;
      let dz = route[nextIdx].z - route[prevIdx].z;
      const lenSq = dx * dx + dz * dz;

      if (lenSq < 1e-10) {
        // Degenerate: no direction, use fallback perpendicular
        dx = 1;
        dz = 0;
      } else {
        const invLen = 1 / Math.sqrt(lenSq);
        dx *= invLen;
        dz *= invLen;
      }

      // Perpendicular in XZ plane (90 deg CCW)
      const perpX = -dz;
      const perpZ = dx;

      const cy = route[i].y + TRACK_Y_OFFSET;

      left.push(
        route[i].x + perpX * HALF_GAUGE,
        cy,
        route[i].z + perpZ * HALF_GAUGE,
      );
      right.push(
        route[i].x - perpX * HALF_GAUGE,
        cy,
        route[i].z - perpZ * HALF_GAUGE,
      );
    }

    return { left, right };
  }

  private rebuildTrack(team: number, route: { x: number; y: number; z: number }[]): void {
    const material = this.getOrCreateMaterial(team);

    // Only treat as closed loop if first and last waypoints are close together
    const first = route[0];
    const last = route[route.length - 1];
    const dx = first.x - last.x;
    const dz = first.z - last.z;
    const isLoop = (dx * dx + dz * dz) < 25; // within ~5 wu

    const { left, right } = this.computeRailOffsets(route, isLoop);

    let count = route.length;
    if (isLoop) {
      // Append first point to close the visual loop
      left.push(left[0], left[1], left[2]);
      right.push(right[0], right[1], right[2]);
      count = route.length + 1;
    }
    const leftPos = new Float32Array(left);
    const rightPos = new Float32Array(right);

    let pair = this.trackLines.get(team);

    if (
      pair &&
      pair.left instanceof THREE.Line && !(pair.left instanceof THREE.LineSegments) &&
      pair.right instanceof THREE.Line && !(pair.right instanceof THREE.LineSegments)
    ) {
      // Update existing geometry in-place for both rails
      this.updateLineGeometry(pair.left, leftPos, count);
      this.updateLineGeometry(pair.right, rightPos, count);
    } else {
      // Remove stale objects
      if (pair) {
        this.scene.remove(pair.left);
        this.scene.remove(pair.right);
        pair.left.geometry.dispose();
        pair.right.geometry.dispose();
      }
      pair = {
        left: this.createLine(leftPos, count, material),
        right: this.createLine(rightPos, count, material),
      };
      this.scene.add(pair.left);
      this.scene.add(pair.right);
      this.trackLines.set(team, pair);
    }
  }

  /** Render only the segments of an enemy track that fall within fog-visible territory. */
  private rebuildEnemyTrack(team: number, route: { x: number; y: number; z: number }[]): void {
    if (!this.fogState) {
      this.removeTrack(team);
      return;
    }

    // Precompute rail offsets for entire route
    const { left: leftAll, right: rightAll } = this.computeRailOffsets(route, true);

    // Collect visible segment vertex pairs for each rail
    const leftVerts: number[] = [];
    const rightVerts: number[] = [];
    const len = route.length;

    for (let i = 0; i < len; i++) {
      const a = route[i];
      const b = route[(i + 1) % len];
      const visA = this.fogState.isVisible(this.playerTeam, a.x, a.z);
      const visB = this.fogState.isVisible(this.playerTeam, b.x, b.z);
      if (visA || visB) {
        const ni = (i + 1) % len;
        // Left rail segment
        leftVerts.push(
          leftAll[i * 3], leftAll[i * 3 + 1], leftAll[i * 3 + 2],
          leftAll[ni * 3], leftAll[ni * 3 + 1], leftAll[ni * 3 + 2],
        );
        // Right rail segment
        rightVerts.push(
          rightAll[i * 3], rightAll[i * 3 + 1], rightAll[i * 3 + 2],
          rightAll[ni * 3], rightAll[ni * 3 + 1], rightAll[ni * 3 + 2],
        );
      }
    }

    if (leftVerts.length === 0) {
      this.removeTrack(team);
      return;
    }

    const leftPos = new Float32Array(leftVerts);
    const rightPos = new Float32Array(rightVerts);
    const material = this.getOrCreateMaterial(team);
    let pair = this.trackLines.get(team);

    if (pair && pair.left instanceof THREE.LineSegments && pair.right instanceof THREE.LineSegments) {
      this.updateLineGeometry(pair.left, leftPos, leftPos.length / 3);
      this.updateLineGeometry(pair.right, rightPos, rightPos.length / 3);
    } else {
      if (pair) {
        this.scene.remove(pair.left);
        this.scene.remove(pair.right);
        pair.left.geometry.dispose();
        pair.right.geometry.dispose();
      }
      pair = {
        left: this.createLineSegments(leftPos, material),
        right: this.createLineSegments(rightPos, material),
      };
      this.scene.add(pair.left);
      this.scene.add(pair.right);
      this.trackLines.set(team, pair);
    }
  }

  private createLine(positions: Float32Array, count: number, material: THREE.LineBasicMaterial): THREE.Line {
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
    geometry.setDrawRange(0, count);
    const line = new THREE.Line(geometry, material);
    line.renderOrder = -1;
    line.frustumCulled = false;
    return line;
  }

  private createLineSegments(positions: Float32Array, material: THREE.LineBasicMaterial): THREE.LineSegments {
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
    const segs = new THREE.LineSegments(geometry, material);
    segs.renderOrder = -1;
    segs.frustumCulled = false;
    return segs;
  }

  private updateLineGeometry(line: THREE.Line | THREE.LineSegments, positions: Float32Array, count: number): void {
    const geo = line.geometry;
    geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
    geo.setDrawRange(0, count);
    geo.computeBoundingSphere();
  }

  private getOrCreateMaterial(team: number): THREE.LineBasicMaterial {
    let material = this.materials.get(team);
    if (!material) {
      material = new THREE.LineBasicMaterial({
        color: TEAM_COLORS[team] ?? 0xffffff,
        transparent: true,
        opacity: TRACK_OPACITY,
        depthTest: true,
      });
      this.materials.set(team, material);
    }
    return material;
  }

  private removeTrack(team: number): void {
    const pair = this.trackLines.get(team);
    if (pair) {
      this.scene.remove(pair.left);
      this.scene.remove(pair.right);
      pair.left.geometry.dispose();
      pair.right.geometry.dispose();
      this.trackLines.delete(team);
    }
  }

  dispose(): void {
    for (const [team] of this.trackLines) {
      this.removeTrack(team);
    }
    for (const [, mat] of this.materials) {
      mat.dispose();
    }
    this.materials.clear();
  }
}
