import * as THREE from 'three';
import type { TrackState } from '@sim/logistics/TrackState';
import type { FogOfWarState } from '@sim/fog/FogOfWarState';

const TRACK_Y_OFFSET = 0.12; // slightly above ground to avoid z-fighting
const TEAM_COLORS = [0x4488ff, 0xff4444];
const TRACK_OPACITY = 0.5;

/**
 * Renders track lines on the ground for each team's active train route.
 * Rebuilds geometry each frame from the TrackState active route — cheap with
 * the ~100 waypoints generated by the Catmull-Rom spline.
 *
 * Enemy tracks are rendered per-segment with fog-of-war filtering:
 * only segments where at least one endpoint is currently visible are shown.
 */
export class TrackRenderer {
  private scene: THREE.Scene;
  private trackLines = new Map<number, THREE.Line | THREE.LineSegments>();
  private materials = new Map<number, THREE.LineBasicMaterial>();
  private playerTeam = 0;
  private fogState: FogOfWarState | null = null;

  constructor(scene: THREE.Scene) {
    this.scene = scene;
  }

  setPlayerTeam(team: number): void {
    this.playerTeam = team;
  }

  setFogState(fogState: FogOfWarState): void {
    this.fogState = fogState;
  }

  sync(trackState: TrackState, teamCount: number): void {
    for (let team = 0; team < teamCount; team++) {
      const ts = trackState.get(team);
      const route = ts.activeRoute;

      if (route.length < 2) {
        this.removeTrack(team);
        continue;
      }

      // Enemy tracks: fog-filtered per-segment rendering
      if (this.playerTeam >= 0 && team !== this.playerTeam) {
        this.rebuildEnemyTrack(team, route);
        continue;
      }

      this.rebuildTrack(team, route);
    }
  }

  private rebuildTrack(team: number, route: { x: number; y: number; z: number }[]): void {
    // Reuse existing Line object, just replace its geometry
    let line = this.trackLines.get(team);
    const material = this.getOrCreateMaterial(team);

    // Build points array (append first point to close the visual loop)
    const count = route.length + 1;
    const positions = new Float32Array(count * 3);
    for (let i = 0; i < route.length; i++) {
      positions[i * 3] = route[i].x;
      positions[i * 3 + 1] = route[i].y + TRACK_Y_OFFSET;
      positions[i * 3 + 2] = route[i].z;
    }
    // Close the visual loop back to the first point
    positions[route.length * 3] = route[0].x;
    positions[route.length * 3 + 1] = route[0].y + TRACK_Y_OFFSET;
    positions[route.length * 3 + 2] = route[0].z;

    if (line && line instanceof THREE.Line && !(line instanceof THREE.LineSegments)) {
      // Update existing geometry in-place
      const geo = line.geometry;
      geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
      geo.setDrawRange(0, count);
      geo.computeBoundingSphere();
    } else {
      // Remove stale object if type changed (e.g. from LineSegments)
      if (line) {
        this.scene.remove(line);
        line.geometry.dispose();
      }
      const geometry = new THREE.BufferGeometry();
      geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
      line = new THREE.Line(geometry, material);
      line.renderOrder = -1;
      line.frustumCulled = false;
      this.scene.add(line);
      this.trackLines.set(team, line);
    }
  }

  /** Render only the segments of an enemy track that fall within fog-visible territory. */
  private rebuildEnemyTrack(team: number, route: { x: number; y: number; z: number }[]): void {
    if (!this.fogState) {
      this.removeTrack(team);
      return;
    }

    // Collect visible segment vertex pairs
    const verts: number[] = [];
    const len = route.length;
    for (let i = 0; i < len; i++) {
      const a = route[i];
      const b = route[(i + 1) % len];
      const visA = this.fogState.isVisible(this.playerTeam, a.x, a.z);
      const visB = this.fogState.isVisible(this.playerTeam, b.x, b.z);
      if (visA || visB) {
        verts.push(a.x, a.y + TRACK_Y_OFFSET, a.z);
        verts.push(b.x, b.y + TRACK_Y_OFFSET, b.z);
      }
    }

    if (verts.length === 0) {
      this.removeTrack(team);
      return;
    }

    const positions = new Float32Array(verts);
    const material = this.getOrCreateMaterial(team);
    let line = this.trackLines.get(team);

    if (line && line instanceof THREE.LineSegments) {
      const geo = line.geometry;
      geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
      geo.setDrawRange(0, positions.length / 3);
      geo.computeBoundingSphere();
    } else {
      // Remove stale object if type changed (e.g. from Line)
      if (line) {
        this.scene.remove(line);
        line.geometry.dispose();
      }
      const geometry = new THREE.BufferGeometry();
      geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
      line = new THREE.LineSegments(geometry, material);
      line.renderOrder = -1;
      line.frustumCulled = false;
      this.scene.add(line);
      this.trackLines.set(team, line);
    }
  }

  private getOrCreateMaterial(team: number): THREE.LineBasicMaterial {
    let material = this.materials.get(team);
    if (!material) {
      material = new THREE.LineBasicMaterial({
        color: TEAM_COLORS[team] ?? 0xffffff,
        transparent: true,
        opacity: TRACK_OPACITY,
        depthTest: true,
      });
      this.materials.set(team, material);
    }
    return material;
  }

  private removeTrack(team: number): void {
    const existing = this.trackLines.get(team);
    if (existing) {
      this.scene.remove(existing);
      existing.geometry.dispose();
      this.trackLines.delete(team);
    }
  }

  dispose(): void {
    for (const [team] of this.trackLines) {
      this.removeTrack(team);
    }
    for (const [, mat] of this.materials) {
      mat.dispose();
    }
    this.materials.clear();
  }
}
