// AUTO-GENERATED by scripts/convert-vox.ts — do not edit manually
// Run `npm run convert-vox` to regenerate from assets/vox/
// Generated 2026-03-02T23:45:04.419Z (0 models)

import type { VoxelModel } from './VoxelModels';

// No .vox models found in assets/vox/. Add entries to assets/vox/models.json to enable.

export const GENERATED_VOXEL_MODELS: Record<string, VoxelModel> = {};
